env:
  global:
    - CC_TEST_REPORTER_ID=3ecc8cde1f07ba7f6f0b70d8d5c52df8221d661b6c28190562fc26f177c1711b
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)


language: php

php:
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.sonar/cache

addons:
  sonarcloud:
    organization: "opendaje"
    token: $SECRET_SONAR_TOKEN

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

  - composer install --optimize-autoloader --no-progress --ansi

jobs:
  include:
    - stage: test
      name: "phpunit"
      script:
        - ./vendor/bin/phpunit --coverage-clover=report-coverage.clover --log-junit=report-test.xml
      # run Sonar scanner and pipe the coverage data to Code Climate
      after_script:
        - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then sonar-scanner; fi
        - ./cc-test-reporter format-coverage -t clover -o coverage/codeclimate.json report-coverage.clover # Format backend coverage
        - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi  # Upload coverage/codeclimate.json


    - stage: test
      name: "code style"
      script: ./vendor/bin/php-cs-fixer fix src/ --dry-run --ansi

    - stage: test
      name: "static analysis - (phpstan)"
      script: ./vendor/bin/phpstan analyse --ansi

    - stage: test
      name: "static analysis - (psalm)"
      script: ./vendor/bin/psalm --show-info=true